name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build /p:AssemblyVersion=1.0.${{ GITHUB_RUN_NUMBER }};FileVersion=1.0.${{ GITHUB_RUN_NUMBER }};PackageVersion=1.0.${{ GITHUB_RUN_NUMBER }} -c Release --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish Nuget
        run: dotnet nuget push src/ClientsRipe/bin/Release/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      - name: Publish Nuget symbols
        run: dotnet nuget push src/ClientsRipe/bin/Release/*.snupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
